// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: music.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PutridParrot.Music {
  public static partial class MusicService
  {
    static readonly string __ServiceName = "music.MusicService";

    static readonly grpc::Marshaller<global::PutridParrot.Music.NotesRequest> __Marshaller_NotesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PutridParrot.Music.NotesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PutridParrot.Music.NotesResponse> __Marshaller_NotesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PutridParrot.Music.NotesResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PutridParrot.Music.NotesRequest, global::PutridParrot.Music.NotesResponse> __Method_Query = new grpc::Method<global::PutridParrot.Music.NotesRequest, global::PutridParrot.Music.NotesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_NotesRequest,
        __Marshaller_NotesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PutridParrot.Music.MusicReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MusicService</summary>
    public abstract partial class MusicServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::PutridParrot.Music.NotesResponse> Query(global::PutridParrot.Music.NotesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MusicService</summary>
    public partial class MusicServiceClient : grpc::ClientBase<MusicServiceClient>
    {
      /// <summary>Creates a new client for MusicService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MusicServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MusicService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MusicServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MusicServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MusicServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PutridParrot.Music.NotesResponse Query(global::PutridParrot.Music.NotesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PutridParrot.Music.NotesResponse Query(global::PutridParrot.Music.NotesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PutridParrot.Music.NotesResponse> QueryAsync(global::PutridParrot.Music.NotesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PutridParrot.Music.NotesResponse> QueryAsync(global::PutridParrot.Music.NotesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MusicServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MusicServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MusicServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Query, serviceImpl.Query).Build();
    }

  }
}
#endregion
